### ISSUE TITLE
UI for the Home Page

### ISSUE THREAD

**Issue by Shruti3004** [Code4GovTech/website#1]
## Description
We need to create the home page for the website [codeforgovtech.in](https://www.codeforgovtech.in/) and implement Cypress tests to ensure its functionality. This task involves designing and developing the home page layout and adding relevant content. The Cypress tests will ensure that the page functions as expected and all components are working correctly.

## Goals
 - [ ] Design and develop the home page layout
 - [ ] Add relevant content to the home page
 - [ ] Implement Cypress tests for the home page

## Expected Outcome
The home page should have an attractive and user-friendly design, showcasing the organization's mission and providing easy navigation. The content should be engaging and informative. The Cypress tests should cover the functionality of the home page, ensuring that all interactive elements and features are working properly.

## Implementation Details
Next.js is used as the framework for the website. Cypress will be the chosen testing framework for the Cypress tests.

## Mockups / Wireframes
https://www.codeforgovtech.in/

## Project
Code for GovTech

## Tech Skills Needed:
JavaScript, Next.js, Cypress

## Mentor(s)
@Shruti3004 

## Complexity
Medium

## Category
UI/UX Enhancements

**Comment by MayaSatishRao** [comment]
@Shruti3004 the website is already built. What needs to be done now? Improvement in the UI ?

**Comment by void-ness** [comment]
> @Shruti3004 the website is already built. What needs to be done now? Improvement in the UI ?

I had a similar query. Here's the response I got. Hoping it solves your concern.
https://github.com/Code4GovTech/website/issues/6#issuecomment-1607506030

The current website is actually built using wix. We need to implement a similar design from scratch using next.js and add the required tests.

**Comment by Shruti3004** [comment]
- Fix the navbar c4gt23 tab (add a dropdown there)
![Screenshot from 2023-07-13 17-46-06](https://github.com/Code4GovTech/website/assets/56133783/fa7e1885-988f-4d58-9b81-dccbb5d702b7)

- Comple website shoud have same width, currently all sections are having different padding
- Blue box aside C4GT logo should have less width and should be at the same height of logo.
    - text inside the box should be center aligned
- The logos should have knowledge partner heading
   - these logos should be responsive
![Screenshot from 2023-07-13 17-48-56](https://github.com/Code4GovTech/website/assets/56133783/be036609-b791-4aa4-9772-d8fedabf0a6c)
- All Headings font size needs to be increased
- Margin between the points and should remove the extra blue space
![Screenshot from 2023-07-13 17-50-38](https://github.com/Code4GovTech/website/assets/56133783/035dd5f6-0e05-4ae5-8e94-59fcef489f0f)
- centering the program report
![Screenshot from 2023-07-13 17-51-50](https://github.com/Code4GovTech/website/assets/56133783/de62cb46-6da8-482c-a07d-26ed749a1fe1)
- Remove the border from card and fix the headings and size of logos
   - also fix its responsiveness
 
![Screenshot from 2023-07-13 17-52-16](https://github.com/Code4GovTech/website/assets/56133783/29f3b193-4942-49fa-a326-a9a693f6dfb3)

- Adding margin bottom in the footer
![Screenshot from 2023-07-13 17-53-02](https://github.com/Code4GovTech/website/assets/56133783/18f34134-90e5-46f7-b89b-f247f92458b6)
- Add specific margins at the end of each section in a way it is responsive
- Fix the sidebar in mobile remove `min-w-[183px] ` instead have `w-[75vw]`

**Comment by MayaSatishRao** [comment]
@Shruti3004 I want to work on this issue. Can you assign this?

**Comment by Shruti3004** [comment]
Hey @MayaSatishRao you can take this issue https://github.com/Code4GovTech/website/issues/4
