### ISSUE TITLE
Bug - Incorrect Page Title

### ISSUE THREAD

**Issue by void-ness** [Code4GovTech/website#19]
## Description
Currently the title of each page is not loading correctly. All the pages are showing the same title as of now. We need to add a different title for each page of the website and implement Cypress tests to ensure its functionality. This task involves fixing the bug and add respective page titles for each page of the website. The Cypress tests will ensure that the page functions as expected and all titles are working correctly.

## Goals
[ ] Find and Fix the Bug causing the incorrect behaviour
[ ] Add relevant titles for each page of the website
[ ] Implement Cypress tests to check if the title is loading correctly

## Expected Outcome
The C4GT website should display correct title for each page. The title should be relevant to the page content, showcasing the organization's mission. The Cypress tests should cover the functionality of the C4GT website, ensuring that all features are working properly.

## Implementation Details
Next.js is used as the framework for the website. Cypress will be the chosen testing framework for the Cypress tests.

## Mockups / Wireframes
https://www.codeforgovtech.in/
(You can refer to page titles from the following website)

## Project
Code for GovTech

## Tech Skills Needed:
JavaScript, Next.js, Cypress

## Mentor(s)
@Shruti3004  

## Complexity
Low

## Category
UI/UX Enhancements

**Comment by inkerton** [comment]
@Shruti3004 I am interested in this issue . Please assign it to me.
