### ISSUE TITLE
UI for the C4GT 2023 page

### ISSUE THREAD

**Issue by Shruti3004** [Code4GovTech/website#2]
## Description
We need to create the C4GT'23 page for the website [c4gt-2023-projects](https://www.codeforgovtech.in/c4gt-2023-projects) and implement Cypress tests to ensure its functionality. This task involves designing and developing the C4GT'23 page layout and adding relevant content. The Cypress tests will ensure that the page functions as expected and all components are working correctly.

## Goals
 - [ ] Design and develop the C4GT'23 page layout
 - [ ] Add relevant content to the C4GT'23 page
 - [ ] Implement Cypress tests for the C4GT'23 page

## Expected Outcome
The C4GT'23 page should have an attractive and user-friendly design, showcasing the organization's mission and providing easy navigation. The content should be engaging and informative. The Cypress tests should cover the functionality of the C4GT'23 page, ensuring that all interactive elements and features are working properly.

## Implementation Details
Next.js is used as the framework for the website. Cypress will be the chosen testing framework for the Cypress tests.

## Mockups / Wireframes
https://www.codeforgovtech.in/c4gt-2023-projects
![Screenshot from 2023-06-22 11-06-16](https://github.com/Code4GovTech/website/assets/56133783/1b71dd94-a10d-4835-9bdd-91f513fc31b7)

## Project
Code for GovTech

## Tech Skills Needed:
JavaScript, Next.js, Cypress

## Mentor(s)
@Shruti3004 

## Complexity
Medium

## Category
UI/UX Enhancements

**Comment by homosapien14** [comment]
hi @Shruti3004 I would like to work on this. could you please assign to me? or should I start and make a PR?

**Comment by KDwevedi** [comment]
comment
