### ISSUE TITLE
UI for the Community Projects page

### ISSUE THREAD

**Issue by Shruti3004** [Code4GovTech/website#4]
## Description
We need to create the Community Projects page for the website [Community Projects](https://c4gt-ccbp-projects.vercel.app/) and implement Cypress tests to ensure its functionality. This task involves designing and developing the Community Projects page layout and adding relevant content. The Cypress tests will ensure that the page functions as expected and all components are working correctly.

## Goals
 - [ ] Design and develop the Community Projects page layout
 - [ ] Add relevant content to the Community Projects page
 - [ ] Implement Cypress tests for the Community Projects page

## Expected Outcome
The Community Projects page should have an attractive and user-friendly design, showcasing the mission and providing easy navigation. The content should be engaging and informative. The Cypress tests should cover the functionality of the Community Projects page, ensuring that all interactive elements and features are working properly.

## Implementation Details
Next.js is used as the framework for the website. Cypress will be the chosen testing framework for the Cypress tests.

## Mockups / Wireframes
[Link](https://c4gt-ccbp-projects.vercel.app/)
![Screenshot from 2023-06-22 11-17-54](https://github.com/Code4GovTech/website/assets/56133783/88a10bd3-8b3c-4e7b-b4bb-7260b075287d)

## Project
Code for GovTech

## Tech Skills Needed:
JavaScript, Next.js, Cypress

## Mentor(s)
@Shruti3004 

## Complexity
Medium

## Category
UI/UX Enhancements

**Comment by Isha988** [comment]
@Shruti3004 I want to work on this issue.

**Comment by hardik-gupta** [comment]
@Shruti3004 I would like to work on this issue. How can I reproduce it?

**Comment by Shruti3004** [comment]
Hey @Isha988 @hardik-gupta yes you can take

**Comment by MayaSatishRao** [comment]
@Shruti3004 this issue is already assigned. If multiple people can be assigned to the same issue, can you assign me as well?

**Comment by Shruti3004** [comment]
Hey @MayaSatishRao https://github.com/Code4GovTech/website/issues/17 I have tagged you here, you can work on this issue, if we didnt get any response on this issue on next 2 days then I'll assign it to you.

**Comment by Shruti3004** [comment]
> @Shruti3004 thank you for assigning me, I would like to work on this.

Great @Isha988, please tag me once you raised the PR

**Comment by hardik-gupta** [comment]
@Shruti3004 thank you for assigning this, looking forward to contrubuting.

**Comment by hardik-gupta** [comment]
@Shruti3004 the Community Program Projects page is already on the C4GT website. Are we implementing the page from scratch or fixing some issues ?

**Comment by Shruti3004** [comment]
Hey @Isha988 are you still woking on the issue? Or I can assign it to @hardik-gupta

**Comment by Isha988** [comment]
> Hey @Isha988 are you still woking on the issue? Or I can assign it to @hardik-gupta

No, I am not, you can assign it to @hardik-gupta

**Comment by hardik-gupta** [comment]
Hello Shurti, I'd be happy to contribute.

**Comment by Shruti3004** [comment]
#31
