### ISSUE TITLE
UI for the C4GT 2022 page

### ISSUE THREAD

**Issue by Shruti3004** [Code4GovTech/website#6]
## Description
We need to create the C4GT'22 page for the website [c4gt-2022-projects](https://www.codeforgovtech.in/copy-of-c4gt-2022) and implement Cypress tests to ensure its functionality. This task involves designing and developing the responsive C4GT'22 page layout and adding relevant content. The Cypress tests will ensure that the page functions as expected and all components are working correctly.

## Goals
 - [ ] Design and develop the C4GT'22 page layout
 - [ ] Add relevant content to the C4GT'22 page
 - [ ] Make it responsive
 - [ ] Implement Cypress tests for the C4GT'22 page

## Expected Outcome
The C4GT'22 page should have an attractive and user-friendly design, showcasing the organization's mission and providing easy navigation. The content should be engaging and informative. The Cypress tests should cover the functionality of the C4GT'22 page, ensuring that all interactive elements and features are working properly.

## Implementation Details
Next.js is used as the framework for the website. Cypress will be the chosen testing framework for the Cypress tests.

## Mockups / Wireframes
[Link](https://www.codeforgovtech.in/copy-of-c4gt-2022)
![Screenshot from 2023-06-22 11-48-25](https://github.com/Code4GovTech/website/assets/56133783/6b4612c0-a9f6-433e-82ab-e8b40b5c2bcc)

## Project
Code for GovTech

## Tech Skills Needed:
JavaScript, Next.js, Cypress

## Mentor(s)
@Shruti3004 

## Complexity
Medium

## Category
UI/UX Enhancements

**Comment by void-ness** [comment]
Hey,
I have a query. It seems like the page already exists for C4GT'22 as mentioned in the issue above. However the page is not responsive. So do we have to only make it responsive?

**Comment by Shruti3004** [comment]
Hey the current site is on wix, and we are shifting it to next.js with test cases and responsivesness, so we have to add the page from scratch in the repo.

**Comment by void-ness** [comment]
So for design, can we refer to the current design only which is the Wix one?

**Comment by Shruti3004** [comment]
Yes

**Comment by void-ness** [comment]
I can handle developing the website as per the design. However, I have limited knowledge related to implementing the Cypress tests. Can I still work on this issue?

**Comment by mustafaazad03** [comment]
Hi @Shruti3004 ,
I am Mustafa Azad, Is this issue still open?
